### ISSUE TITLE
distance in nearby query limited to 500m

### ISSUE THREAD

**Issue by misteu** [derhuerst/bvg-rest#1]
It seems to work only up to 500m, when I say e.g. distance=1000 it still show only stations up to 500m

**Comment by derhuerst** [comment]
Can you give me an example to reproduce this?

**Comment by misteu** [comment]
it seems to be also dependent on the location.
E.g. a request with this query (Alexanderplatz): 
https://1.bvg.transport.rest/stations/nearby?latitude=52.5215595&longitude=13.408969
results in a response with every station within 2km (as expected)

If I put in the distance parameter with e.g. for 500m -> https://1.bvg.transport.rest/stations/nearby?latitude=52.5215595&longitude=13.408969&distance=500

the last station I get is at 318m. Below 318m I can define the distance, above that it does not have any effect.

For other locations, the "critical value" is different. E.g. this one (Ostbahnhof): https://1.bvg.transport.rest/stations/nearby?latitude=52.5105389&longitude=13.432794
vs.
https://1.bvg.transport.rest/stations/nearby?latitude=52.5105389&longitude=13.432794&distance=1500

the last station I see has a distance of 536m.
