### ISSUE TITLE
v6.bvg.transport.rest - not available since Friday

### ISSUE THREAD

**Issue by tawissus** [derhuerst/bvg-rest#17]
Example:
https://v6.bvg.transport.rest/locations?poi=false&addresses=false&query=mehringdamm

<img width="781" alt="image" src="https://user-images.githubusercontent.com/1453423/236683208-772cd404-14f4-4ae5-9f51-71ac193f947b.png">

The status page shows something different.
https://stats.uptimerobot.com/57wNLs39M/793274554

**Comment by marisbaier** [comment]
I‘ve just started running a traffic display in my university for about two days before this issue came up :D How unfortunate, I hope this gets fixed

**Comment by derhuerst** [comment]
`v6.bvg.transport.rest` should be available again, with [the usual pattern of occasional downtimes](https://stats.uptimerobot.com/57wNLs39M/793274554). Does it work for you?

**Comment by tawissus** [comment]
Thank you. Everything works again for me.

**Comment by derhuerst** [comment]
I'll close this. Please re-open if you encounter (non-temporary) downtimes again within the next days!

**Comment by marisbaier** [comment]
Thank you! :)

**Comment by tawissus** [comment]
Hey everyone, v6.bvg.transport.rest is offline again since yesterday evening. If you find time, you can have a look. 🙂

**Comment by derhuerst** [comment]
It should be working again now. Please continue to let me know whenever some API is down for longer than a few minutes!

In order to reduce load on the underlying "upstream" BVG/DB/VBB HAFAS APIs, I [have reduced](https://github.com/public-transport/transport.rest/commit/f97467aed8d65a8e1facca0c64d54316d6018d33) the rate limit of `{v5,v6}.{bvg,db,vbb}.transport.rest` to 60 requests per minute (each).

**Comment by tawissus** [comment]
Thanks. It's fine again. 🤩

**Comment by tawissus** [comment]
It's down again (503). 
Could you check it? 😄

**Comment by tawissus** [comment]
Hello,
v6 is down again. 🤠

**Comment by tawissus** [comment]
Heyho @derhuerst,
Have you had time to look?

**Comment by tawissus** [comment]
Thank you. It's up again.

**Comment by derhuerst** [comment]
As documented in https://github.com/derhuerst/bvg-rest/issues/22#issuecomment-2375329808: In the past weeks, it was down due to https://github.com/public-transport/hafas-client/issues/324.
