### ISSUE TITLE
All query requests returns 503

### ISSUE THREAD

**Issue by ahmed-ramzi** [derhuerst/bvg-rest#18]
I am trying to make a request like 
`https://v6.bvg.transport.rest/stops/900017101/departures?results=5`
or 
`https://v6.bvg.transport.rest/locations?poi=false&addresses=false&query=mehringdamm`

And it returns 503

![CleanShot 2023-09-19 at 19 52 28](https://github.com/derhuerst/bvg-rest/assets/82296979/f2fff733-8d92-40e0-b72a-55c5633510f8)

**Comment by ahmed-ramzi** [comment]
It should be resolved now. Thank you :)

**Comment by derhuerst** [comment]
Thanks for reporting this. https://github.com/derhuerst/bvg-rest/issues/17 is a very similar report.

Unfortunately, most of the time, I can't do anything about it.
