### ISSUE TITLE
Remarks of type warning not available in other languages

### ISSUE THREAD

**Issue by Tiam-Abderezai** [derhuerst/bvg-rest#20]
Is it possible to add warning remarks in other languages? When I query the URL by language, say "es" or "fr" for example, it defaults to German for the "text" and "summary" fields of the "warning" type of "remakrs". It works for English or German, but not other languages.

Remarks like for "hints" translate to other languages just fine however.

Thank you for all your work btw, really awesome API.

**Comment by derhuerst** [comment]
Thanks for asking.

`bvg-rest` uses `hafas-rest-api`, which just passes the `language` query parameter as-is as `opt.language` into `bvg-hafas`, which in turn is just a thin layer around [`hafas-client`'s `bvg` profile](https://github.com/public-transport/hafas-client/tree/6/p/bvg). `hafas-client` merely sends the language code to HAFAS. So unfortunately, **we cannot control which languages BVG's HAFAS API returns translated remarks for**.

It seems like that, for some languages (I think `de` & `en`), all remarks have translations – both `hint`, which are automatically assigned, and `warning`, which are manually assigned by an operator. I tried `tr`, `pl` and `ar`, but they seem to have only a fraction of remarks translated.

There is a thing you can do: Email them and ask about support in their official mobile app for e.g. Arabic. If they start translating their remarks, they will immediately show up as translated in `v6.bvg.transport.rest`, too.

If that doesn't answer your question, please re-open this Issue.
