### ISSUE TITLE
Server return 503

### ISSUE THREAD

**Issue by ahmed-ramzi** [derhuerst/bvg-rest#22]
Hi there, it seems like the service is down
When querying data. For example,

https://v6.bvg.transport.rest/stops/900013102/departures?direction=900014101&duration=10

The result I get back

```shell
> GET /stops/900013102/departures?direction=900014101&duration=10 HTTP/2
> Host: v6.bvg.transport.rest
> user-agent: insomnia/9.3.3
> accept: application/json

* TLSv1.2 (IN), TLS header, Supplemental data (23):

< HTTP/2 503 
< alt-svc: h3=":443"; ma=2592000
< ratelimit-policy: 60; w=60
< server: Caddy
< content-length: 0
< date: Tue, 06 Aug 2024 14:00:28 GMT
``` 

In the home route however, the responses return 200

**Comment by billypchan** [comment]
I changed the url from BVG to vbb and got response. E.g.:


https://v6.vbb.transport.rest/locations?poi=false&addresses=false&query=mehringdamm

**Comment by ahmed-ramzi** [comment]
@billypchan Yes, I noticed that. However, by the time I posted this the VBB service was also down and returned 503, but it got back up in a few hours. I am just curious why the BVG service still doesn't work.

**Comment by matriphe** [comment]
I suspected that BVG changed their API due to their new mobile app. I also reported the issue in #23 as well.

**Comment by ippen** [comment]
> I changed the url from BVG to vbb and got response. E.g.:
> 
> https://v6.vbb.transport.rest/locations?poi=false&addresses=false&query=mehringdamm

This currently seems to be the workaround as a drop in replacement.
Simply change https://v6.bvg.transport.rest with https://v6.vbb.transport.rest

**Comment by gekberlin** [comment]
Unfortunately, when you use the VBHAS client data, there is no occupancy of the product given. So using the VBB client is totally fine for a short work round, but there is still a slight difference in the response data structure.

**Comment by gekberlin** [comment]
@derhuerst any chance to make an update (like there: https://github.com/public-transport/transport-apis/pull/84) in the background to get the v6.bvg back to life?

**Comment by derhuerst** [comment]
I have fixed the underlying issue in `hafas-client`, but I still need to publish it to npm and then use it in `v6.bvg.transport.rest`.

**Comment by derhuerst** [comment]
The fix is deployed now. 🎉

**Comment by hg421** [comment]
Could you update the docker image too?
