### ISSUE TITLE
API service not working v6.bvg.transport.rest (is down)

### ISSUE THREAD

**Issue by Kardelio** [derhuerst/bvg-rest#25]
Hi there,
Not sure where the right place is to post/report this, so I hope it is ok here...

Since last week the API service v6.bvg.transport.rest is down and I (and all other consumers i have spoke to) receive only 503 status codes after waiting for a while for the request to complete.

The up tracker (status tracker) https://stats.uptimerobot.com/57wNLs39M/793274554 is showing it as UP and OPERATIONAL but this is incorrect.

Also the swagger link is broken too (https://petstore.swagger.io/?url=https%3A%2F%2Fv6.bvg.transport.rest%2F.well-known%2Fservice-desc%0A) im guessing this is related aswell.

There doesnt seem to have been any change in this repo recently, so maybe its the underlying data from HAFAS? or something like that?
@derhuerst maybe you know? (sorry you seem to be the main point of contact on this front haha sorry if im wrong) <3

**Comment by argl** [comment]
Same problem here, tried from different locations, always a 503 response. I do not know how the status page does its thing, but currently it is not very useful. I any case, great work, enjoying the APIs!

**Comment by behring5** [comment]
same probleme here.
I've noticed that not all endpoints stopped working.
In my tool I'm using `https://v6.db.transport.rest/stops` which is not working

But  `https://v6.db.transport.rest/locations` is still responding with data.

You can test it by yourself here https://petstore.swagger.io/?url=https%3A%2F%2Fv6.db.transport.rest%2F.well-known%2Fservice-desc%0A

**Comment by behring5** [comment]
I think I found the issue(s).
1. The API domain has changed
It NOT `https://v6.bvg.transport.rest/` anymore, its now `https://v6.db.transport.rest/`

2. the station IDs seem to have changed. 
So if you're using a specific one of a station (which I do with my tool), check for the latest ID with [/locations](https://petstore.swagger.io/?url=https%3A%2F%2Fv6.db.transport.rest%2F.well-known%2Fservice-desc%0A#/default/get_locations)

Edit: The structure of the responding JSON seems to have changed a bit as well.

That's it.  -_-
Happy debugging

**Comment by argl** [comment]
Isn't that the deutsche bahn endpoint? I am looking for the bvg/vbb endpoint, which still does not work.

**Comment by FredNandrin** [comment]
I made a few tests.
The BVG server does return error using the Hafas client version.
The version is fixed on Hafas vbb client.
I left some comment there
[Hafas client](https://github.com/public-transport/vbb-hafas/issues/34)

Hope this will help..

**Comment by FredNandrin** [comment]
Fix is available but need to be approved I guess...
https://github.com/public-transport/hafas-client/pull/323

**Comment by derhuerst** [comment]
This should be fixed by now.
