### ISSUE TITLE
each Docker container should generate a new hafas-client install ID

### ISSUE THREAD

**Issue by theottm** [derhuerst/bvg-rest#4]
1.bvg.transport.rest seems down

> {"error":true,"msg":"no connection available"}%

**Comment by derhuerst** [comment]
Thanks for the report! The upstream BVG endpoint (that `1.bvg.transport.rest` wraps around) have blocked the IP address for my server, so `1.bvg.transport.rest` [returns "service unavailable" responses](https://status.transport.rest/781627008).

This can be solved by migrating the server to a new IP or using a different server. Let me know if you have one available.

**Comment by theottm** [comment]
I have a sleeping EC2 instance that could be used for that.

Tell me how I should have the service running.

I tried to run the docker container as described [here](https://github.com/derhuerst/vbb-rest/#via-docker) with no success.  The result message is the same. Never worked with node so I did not tried the npm solution yet, but I could.

**Comment by derhuerst** [comment]
> I have a sleeping EC2 instance that could be used for that.

Cool!
 
> Tell me how I should have the service running.

How would you like to run the service? Via Docker or manually via common Node.js tooling?
 
> I tried to run the docker container as described [here](https://github.com/derhuerst/vbb-rest/#via-docker) with no success. The result message is the same.

Does that mean you get the "no connection available" message back?

I've just tried and running locally via Docker works fine, I get data back. (I checked with `curl 'http://localhost:3000/stations/900000100001/departures?duration=1'`.)

**Comment by derhuerst** [comment]
[Seems like the service has recovered](https://status.transport.rest/781627008). Nevertheless, it's helpful to know a) that you're willing to host it and b) what problems you face with the setup.

**Comment by theottm** [comment]
Yes I did receive the same error message.
But if it worked for you I will try to the Docker container again.

**Comment by theottm** [comment]
Oh great !
I will still try to set up the server, so we can use it in case of another problem :)

**Comment by theottm** [comment]
It's down again... maybe we should try a rotating IP solution with a proxy list or something.

For now I am not able to run the container properly on my local machine
`curl 'localhost:3000/journeys?from=900000017104&to=900000017101' `
while the container is running returns me : 
`{"error":true,"msg":"VBB error: Service Unavailable"}                                                                                                                                                                                                                                                                                                                                    `

**Comment by derhuerst** [comment]
> `VBB error: Service Unavailable`

That is their endpoint reporting downtime, not your IP being blocked. Errors like `ECONNRESET` or `ETIMEDOUT` hint that your IP has been blocked.

**Comment by derhuerst** [comment]
We investigated further and found a bug: The [install-unique ID generated by `hafas-client`](https://github.com/public-transport/hafas-client/blob/73261e99b499b9c0d4e8906d8f2715380396cca5/lib/generate-install-id.js) (which is a dependency of `bvg-rest`) is being built into the *Docker image*. It should be regenerated on *container start* in addition.

@theottm Would you mind submitting the fix?

**Comment by theottm** [comment]
Thanks, didn't find the time today. Glad it works again :)
