### ISSUE TITLE
URL in header is out-of-date

### ISSUE THREAD

**Issue by fspoettel** [derhuerst/bvg-rest#8]
Hey, thank you for your work with this project! I noticed that the header URL `https://1.bvg.transport.rest` is out-of-date and should read `https://2.bvg.transport.rest`.

**Comment by derhuerst** [comment]
Thanks for reporting! In which header?

**Comment by fspoettel** [comment]
It's the website field in this Github repo, see screenshot below

![Screenshot from 2020-04-25 20-02-18](https://user-images.githubusercontent.com/1682504/80287085-ee991580-871e-11ea-93f9-5e6f01d42b8f.png)

**Comment by derhuerst** [comment]
Fixed, thanks!
